meta_product_name: "Zuza Zuber"
meta_title: "Zuza Zuber - read, collaborate, hang out"
meta_description: "Professional software developer and teacher based in Berlin. Read my blog, get to know me and collaborate on amazing projects!"
meta_image: "cover.png" # should exist in `app/assets/images/`
